Health = 3; //amount of health the monster has
FullDamageCooldown = 20; //
CurrentDamageCooldown = FullDamageCooldown; //
MoveSpeed = 4; //movement speed (in pixels per step) of the monster 
AggroRange = 250; //range at which the monster will start engaging the player
StopRange = 100; //range at which the monster will stop persuing the player and just fire
FleeRange = 50; //range at which the monster will go get help (or panic)
ProjectileDamage = 1; //amount of damage the monster's projectiles do
ProjectileRange = 250; //range at which the monster will fire projectiles
ProjectileCooldown = 2; //amount of time (in seconds) between firing a projectile
CanFire = true; //flag indicating whether the monster can fire a projectile
Aggro = false; //flag indicating whether the player is in aggro range
SearchTime = 2; //amount of time the monster will search for the player (time between disengaging and continuing patrol)
Returning = false; //flag that indicates whether the monster is returning to its patrol
GettingHelp = false; //flag that indicates whether the monster is getting help or not
myHurtbox = instance_create_depth(x,y,-1000,obj_enemy_hurtbox);