Health = 3; //amount of health the monster has
FullDamageCooldown = 20;
CurrentDamageCooldown = FullDamageCooldown;
InvincibilityCooldown = 0.5; //amount of time (in seconds) the monster will be invincible after being hit
CanDamage = true; //flag indicating whether the monster can be damaged or not (toggles invincibility)
MoveSpeed = 4; //movement speed (in pixels per step) of the monster 
AggroRange = 250; //range at which the monster will start engaging the player
MeleeDamage = 1; //amount of damage the monster does by touching the player
ProjectileDamage = 1; //amount of damage the monster's projectiles do
ProjectileRange = 250; //range at which the monster will fire projectiles
ProjectileCooldown = 2; //amount of time (in seconds) between firing a projectile
CanFire = true; //flag indicating whether the monster can fire a projectile
Aggro = false; //flag indicating whether the player is in aggro range
SearchTime = 2; //amount of time the monster will search for the player (time between disengaging and continuing patrol)
